# Generated by Django 5.0.3 on 2024-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_author_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья'), ('NT', 'Объявление')], default='AR', max_length=2, verbose_name='Тип публикации'),
        ),
    ]
