# Generated by Django 5.0.3 on 2024-04-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
