# Generated by Django 5.0.3 on 2024-04-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
