# Generated by Django 5.0.3 on 2024-04-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_postcategory_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='category_through',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='post_through',
        ),
    ]
